name: Horusec

on:
  push:
    branches: [ "staging" ]
  pull_request:

jobs:
  scan-and-upload:
    runs-on: ubuntu-latest
    name: Scan with Horusec 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Cache Horusec dependencies
    - name: Cache Horusec image
      uses: actions/cache@v3
      with:
        path: ~/.cache/horusec
        key: horusec-${{ runner.os }}-${{ hashFiles('Dockerfile', '.horusecconfig') }}

    # Run Linting (Optional)
    - name: Run Linting
      run: |
        eslint . --fix

    # Install and run Horusec
    - name: Run Horusec
      run: |
        curl -fsSL https://horusec.io/bin/install.sh | bash
        horusec start -p ./ -o=json -O=horusec-report.json --log-level=info

    # Check for critical vulnerabilities
    - name: Check Horusec report for critical vulnerabilities
      run: |
        vulnerabilities=$(jq '.vulnerabilities | map(select(.severity == "High" or .severity == "Critical")) | length' horusec-report.json)
        if [ "$vulnerabilities" -gt 0 ]; then
          echo "Critical vulnerabilities found!" && exit 1
        fi

    # Upload report to DefectDojo
    - name: Upload report to DefectDojo
      run: |
        curl -X POST "http://localhost:8080/api/v2/import-scan/" \
        -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_TOKEN }}" \
        -F "file=@horusec-report.json" \
        -F "engagement=$DEFECTDOJO_ENGAGEMENT_ID" \
        -F "scan_type=Horusec"

    # Notify Slack on failur
    - name: Notify Slack if critical vulnerabilities found
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      with:
        slack_webhook_url: ${{



