name: Horusec

on:
  push:
    branches: [ "staging" ]
  pull_request:

jobs:
  checking_code:
    runs-on: ubuntu-latest
    name: Horusec Scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Horusec
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/scripts/install.sh | bash
          horusec version

      - name: Run Horusec scan
        run: |
          horusec start -p ./ \
            -o=json \
            -O=horusec-report.json \
            --log-level=info \
            --config-file-path=horusec-config.json

      - name: Upload Horusec report as artifact
        uses: actions/upload-artifact@master
        with:
          name: horusec-report
          path: horusec-report.json


